# 配置文件 autoFreeze v1.1
# 设为0即禁用
# 单位：游戏刻 tick (1/20s)
# Configuration File
# Set to 0 to disable
# Unit: Game tick (1/20s)

# 在日志中和控制台记录在线人数的时间间隔
# Interval for logging the number of online players in the console and logs
logPlayerCountInterval: 0

